server:
  port: 10001

spring:
  application:
    name: configurationservice
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: D:\workspace\project-forniture-web-store\configurations
