server:
  port: 10003

spring:
  application:
    name: gatewayservice
  profiles:
    active: dev

  config:
    import: optional:configserver:http://localhost:10001

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:10002/eureka
    registerWithEureka: true
    fetchRegistry: true

