server:
  port: 10002

spring:
  application:
    name: discoveryservice

  security:
    user:
      name: admin
      password: admin

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:10002/eureka
    registerWithEureka: false
    fetchRegistry: false
