
security:
  claims:
    header-authorities: Authorities
    separator: --
  token:
    key: qwerty123456
    type: Bearer
    header-name: token
    validity: 18000000
    
    
management:
  endpoints:
    web:
      exposure:
        include: "*"