server:
  port: 10005

spring:
  application:
    name: productservice
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:10001

  datasource:
    url: jdbc:mysql://localhost:33062/productdatabase
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

logging:
  level:
    root: info

eureka:
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://admin:admin@localhost:10002/eureka
    registerWithEureka: true
    fetchRegistry: true
