version: "3.8"

services:

  rabbitmq:
    image: rabbitmq:3-management
    mem_limit: 700m
    hostname: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - fornitureweb

  userdatabase:
    image: mysql
    mem_limit: 700m
    hostname: database
    ports:
      - "33061:3306"
    environment:
      MYSQL_DATABASE: userdatabase
      MYSQL_ROOT_PASSWORD: root
    networks:
      - fornitureweb

  productdatabase:
    image: mysql
    mem_limit: 700m
    hostname: database
    ports:
      - "33062:3306"
    environment:
      MYSQL_DATABASE: productdatabase
      MYSQL_ROOT_PASSWORD: root
    networks:
      - fornitureweb

networks:
  fornitureweb: